### ISSUE TITLE
White Haired Ellesime

### ISSUE THREAD

**Issue by Sampsca** [GwendolyneFreddy/Infinity-Animations#5]
I have taken a crack at converting NELLEG2.bam to match the white haired version of NELLEG1.bam.  After trying for a couple days using more traditional image editing techniques with ImageMagick, I was unable to produce anything acceptable.  After a bunch of noodling, I extracted the frames from NELLG1 and NELLG11 thru NELLG15, and combined them into a single animation.  These frames match NELLEG1 almost 1:1 (I had to manually edit 5 frames), except for the color.  The NELLG1* frames used different color tones on the clothing/body and red hair, whereas NELLEG1 had the desired clothing/body colors and white hair.  I then wrote a custom algorithm that for each pixel in each image, calculated the difference in RGB colorspace from the source color to the destination (desired) color (excluding the transparent and shadow colors).  I then averaged these total differences for each source color, and applied those differences to the palette of NELLEG2.bam (the deltas from the closest source color if that color was not in the original palette).  Sounds simple, but was more than a bit complex to actually implement.  Here are the results:

The original (left), the theoretically correct version (center), my version (right)
![Original](https://user-images.githubusercontent.com/7087647/115932730-1ebee580-a453-11eb-9c78-04c2d81377e3.png) ![Correct](https://user-images.githubusercontent.com/7087647/115932727-1e264f00-a453-11eb-9e56-8396582bb1cf.png) ![MyVersion](https://user-images.githubusercontent.com/7087647/115932729-1e264f00-a453-11eb-9b36-a0942efc119e.png)
(This particular image is a worst case in terms of hair color, but doesn't fully demonstrate how much closer the cape and clothing color is to the target values.)

As you can see, my technique by-and-large produced the desired results.  However, you will notice that brown pixels erroneously remained in the white hair (this particular frame is one of the worst).  This is because those colors of brown and used elsewhere in the images far more frequently, and those occurrences are on average both consistent and correct.  For the life of me I can't come up with a better solution other than manually editing all 431 distinct frames pixel by pixel (which I'm not particularly interested in doing).  Any suggestions?

[NELLEG2.zip](https://github.com/GwendolyneFreddy/Infinity-Animations/files/6368246/NELLEG2.zip)

**Comment by GwendolyneFreddy** [comment]
Sorry for the delay, but I was very busy testing NI new release (it will detect if Infinity Animations vb5 or v6.0.0 and later is installed).

Thanks for this tremendous work. I tested it in-game and, despite I knew which part of the hair to check, I must say that it renders perfectly, even when zoomed in EE games. :wink:

I don't think players will notice the dark colors, and I definitively erased all the animation frames I had exported to fix them manually.

In any case, I [updated](https://github.com/GwendolyneFreddy/Infinity-Animations/commit/1d417992261683c228f06d6689ad2ebeb515f694) the file in this repo.
